<?php

namespace App\Http\Controllers\User;

use App\Models\Task;
use PhpOffice\PhpWord\IOFactory;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class OfficeController extends Controller
{
    public function createDoc(){
        $word = new \PhpOffice\PhpWord\PhpWord();
        $section = $word->addSection();
        $html = " ";

        \PhpOffice\PhpWord\Shared\Html::addHtml($section, $html, false, false);


        $objWriter = \PhpOffice\PhpWord\IOFactory::createWriter($word, 'Word2007');
        try{
            $objWriter->save(storage_path('helloWorld.docx'));

        }catch(Exception $e){

        }
        return response()->download(storage_path('helloWorld.docx'));
    }

    public function uploadDoc(Request $request, $id){


        $phpWord = IOFactory::createReader('Word2007')->load($request->file('file')->path());
        $objWriter = \PhpOffice\PhpWord\IOFactory::createWriter($phpWord, 'HTML');
        $objWriter->save('docs.html');

        $body =  file_get_contents('docs.html');

        $body = str_ireplace("<title>PHPWord</title>","", $body );
        $body = str_ireplace("<!-- Generated by PHPWord -->","", $body );


        $task               = Task::find($id);
        $task->body         = $body;
        $task->status       = 'delivered';
        $response           = $task->save();

        if ($response){
            return redirect()->route('user.tasks')->with("success", "Completed Successfully.");
        }else{
            return redirect()->back()->withInput($request->all())->with("error", "Something went wrong. Please try again.");
        }
    }
}
